<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FunEvents.Application\FunEvents.Application.csproj" />
    <ProjectReference Include="..\FunEvents.Domain\FunEvents.Domain.csproj" />
  </ItemGroup>

</Project>
